### ISSUE TITLE
using fold markers without numbered levels and still getting an outline. Is it somehow possible ?

### ISSUE THREAD

**Issue by m040601** [vim-voom/VOoM#10]
Thanks for all your effort in this great plugin.

Apologies if my question seems silly or pretty obvious.
I searched the documentation and issues but could not find an answer to my itch.

I am considering the simple default case of using vim to outline a simple text file with the option foldmethod=marker. Very often, and confortably, I use "zf" with motion or a visual selection .
Vim will insert the markers for me.  It will append the default start and end marker,
But vim will not, of course, append any numbers to it.

That's enough for me in most cases. I dont need to go there and append 1,2 or 3 to that '{{{' .
I also dont like numbers that much, because I shuffle and rearrange my text very often, and it's difficult to keep track of them.I can still nest more folders. And I confortably toggle them with all the vim 'z' commands, all looking at the same buffer window.

Then my notes file, starts to grow and grow, and I would like to see an extra TOC or outline in a different window. Thats the thing that  voom does very well. Except, that since I dont have any numbers after all those  '{{{' markers, voom isnt able to do any outline.

 I know that this is how voom is supposed to work : 
> VOoM scans only for _start_ fold markers with level numbers. End fold markers
> with levels and fold markers without levels are ignored. This assumes that the
> user follows certain rules of using fold markers. These rules make a lot of
> sense and are similar to recommendations given in Vim help (|fold-marker|).
> 

I was wondering how could I still get an outline from voo, without having to edit my file and append numbers, after the start marker '{{{'

Thanks in advance

**Comment by vim-voom** [comment]
What I wrote in help file is true. VOoM, when in an fmr mode, only scans
for **start fold markers followed by a number**: `{{{1, {{{2, {{{3, ...`.
All other kinds of fold markers are ignored. I will not change VOoM to
support them because it would be a mess and I am not interested.
If you insist on having lots of nested `{{{...}}}` or `}}}1, }}}2, ...`
you will have to use something else. Most non-code writers probably
choose Markdown, Pandoc, AsciiDoc, etc instead of Vim fold markers.

I wrote plugin to make it easier to insert `{{{1, {{{2, ...`:
http://www.vim.org/scripts/script.php?script_id=2891

Other Vim outlining plugins:
http://vim.wikia.com/wiki/Script:List_of_scripts_for_outlining?useskin=monobook

This is a nice plugin and a good idea. It can make TOC out of `{{{...}}}`:
http://www.vim.org/scripts/script.php?script_id=3240
It could probably be done by VOoM, but I will not do it. It would have
to be a read-only outline, no outline operations.

There is also Leo outliner. Leo's sections are like Vim's regions folded
with `{{{...}}}`. You write `<<SectionName>>` and insert subnode with
headline `<<SectionName>>`: 
http://leoeditor.com/tutorial-programming.html#markup

**Comment by m040601** [comment]
great, thanks !
I understand your point.

Didnt know about that alternative, vim_FoldDigest, or your own create_start_fold_marker.vim plugins.
Nowadays I avoid looking into vim.org and only search github for plugins that seem to be 
actively maintained.
