### ISSUE TITLE
Voom jumps in text do not go to history of movements

### ISSUE THREAD

**Issue by roper79** [vim-voom/VOoM#13]
- Go to a place in text.
- Switch to VOom window and jump to another place in text.
- Go to another place in text.
- CTRL-O should take you to the place jumped from VOom, but it does not.

**Comment by vim-voom** [comment]
I am aware of this issue. You have to set a mark manually with m' or m`
if you want to go back to that place with Ctrl-o.

The problem is that when using VOoM Tree buffer for navigation, there is
always a lot of jumping back and forth between the source buffer and
tree buffer. There are situations when a jump mark is useful, but in
many cases I do not want jump marks to be set, for example when
repeatedly pressing Up and Down arrow keys in the Tree buffer. I thus
decided to not set any jump marks at all when outline is navigated from
Tree buffer (the code uses keepj a lot).

**Comment by roper79** [comment]
Thanks a lot for the explanation, the decision makes sense.
