### ISSUE TITLE
Suggestion: nicer foldtext in tree window

### ISSUE THREAD

**Issue by Vrihub** [vim-voom/VOoM#9]
Suggestion: the tree window looks nicer (to me) if you right-align the number of folded lines displayed in headlines (`/xyz`).

You can achieve this changing the foldtext definition in `/autoload/voom.vim` to:

    setl foldtext=getline(v:foldstart).repeat('\ ',g:voom_tree_width-strchars(getline(v:foldstart))-6).'/'.(v:foldend-v:foldstart)

(subtracting 6 allows for up to 4 digits for the displayed number)

BTW, I prefer having the number in parentheses:

    setl foldtext=getline(v:foldstart).repeat('\ ',g:voom_tree_width-strchars(getline(v:foldstart))-6).'('.(v:foldend-v:foldstart).')'

Thanks for this great plugin!

**Comment by vim-voom** [comment]
Sorry, will not change. I like it too, but I am used to the current look.
I would use winwidth(0) instead of g:voom_tree_width:

    setl foldtext=getline(v:foldstart).'\ \ '.repeat('\ ',winwidth(0)-strchars(getline(v:foldstart))-8).'('.(v:foldend-v:foldstart).')'

VOoM has a mechanism to allow users to customize the appearance of Tree
buffers. No need to edit the source. When a new Tree buffer is
created, its filetype is set to "voomtree". So in your local Vim folder
create file `after/ftplugin/voomtree.vim`
and put your foldtext there. It will override default foldtext.

I found a couple small bugs while testing this. Window-local settings in
ftplugin/voomtree.vim and similar are lost when Tree windows are split
and created manually. I will release v5.3 with a fix.

**Comment by Vrihub** [comment]
Very good to know, thanks!

**Comment by vim-voom** [comment]
Closing. Not an issue.
